config/routes.rb
Rails.application.routes.draw do
  resources :killers

end

app/models/killer.rb
class Killer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/killers_controller.rb
class KillersController < ApplicationController
  before_action :set_killer, only: [:show, :edit, :update, :destroy]

  session :off, only: :index

  # GET /killers
  # GET /killers.json
  def index
    @killers = Killer.all

    respond_to do |format|
      format.html do
        reset_session
        val = 20 + Random.rand(11)
        cookies['_CookieKiller_session'] = { value: '', expires: 1.year.ago, httponly: true }
        render :index
      end
    end
  end

  # GET /killers/1
  # GET /killers/1.json
  def show
  end

  # GET /killers/new
  def new
    @killer = Killer.new
  end

  # GET /killers/1/edit
  def edit
  end

  # POST /killers
  # POST /killers.json
  def create
    @killer = Killer.new(killer_params)

    respond_to do |format|
      if @killer.save
        format.html { redirect_to @killer, notice: 'Killer was successfully created.' }
        format.json { render :show, status: :created, location: @killer }
      else
        format.html { render :new }
        format.json { render json: @killer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /killers/1
  # PATCH/PUT /killers/1.json
  def update
    respond_to do |format|
      if @killer.update(killer_params)
        format.html { redirect_to @killer, notice: 'Killer was successfully updated.' }
        format.json { render :show, status: :ok, location: @killer }
      else
        format.html { render :edit }
        format.json { render json: @killer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /killers/1
  # DELETE /killers/1.json
  def destroy
    @killer.destroy
    respond_to do |format|
      format.html { redirect_to killers_url, notice: 'Killer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_killer
      @killer = Killer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def killer_params
      params[:killer]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/killers_helper.rb
module KillersHelper
end

app/views/killers/_form.html.erb
<%= form_for(@killer) do |f| %>
  <% if @killer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@killer.errors.count, "error") %> prohibited this killer from being saved:</h2>

      <ul>
      <% @killer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/killers/edit.html.erb
<h1>Editing killer</h1>

<%= render 'form' %>

<%= link_to 'Show', @killer %> |
<%= link_to 'Back', killers_path %>

app/views/killers/index.html.erb
<h1>Listing killers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @killers.each do |killer| %>
      <tr>
        <td><%= link_to 'Show', killer %></td>
        <td><%= link_to 'Edit', edit_killer_path(killer) %></td>
        <td><%= link_to 'Destroy', killer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Killer', new_killer_path %>

app/views/killers/new.html.erb
<h1>New killer</h1>

<%= render 'form' %>

<%= link_to 'Back', killers_path %>

app/views/killers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_killer_path(@killer) %> |
<%= link_to 'Back', killers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookieKiller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>

<%= yield %>

</body>
</html>